// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2r9-rWQFbmSo4S9_H9yk5e_7qOHHw75g',
    appId: '1:37262681762:android:962c9b4376e87be396d9fb',
    messagingSenderId: '37262681762',
    projectId: 'hahu-hoheng-fitfun',
    storageBucket: 'hahu-hoheng-fitfun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtcFjkYWR7tX8QjBK9ZqEhw2Q3lICm38',
    appId: '1:37262681762:ios:78589a02a03777e896d9fb',
    messagingSenderId: '37262681762',
    projectId: 'hahu-hoheng-fitfun',
    storageBucket: 'hahu-hoheng-fitfun.appspot.com',
    iosClientId: '37262681762-sssqisboahethkar7tci57aibqev3pbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUjianLearningx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtcFjkYWR7tX8QjBK9ZqEhw2Q3lICm38',
    appId: '1:37262681762:ios:f49582b94342828996d9fb',
    messagingSenderId: '37262681762',
    projectId: 'hahu-hoheng-fitfun',
    storageBucket: 'hahu-hoheng-fitfun.appspot.com',
    iosClientId: '37262681762-1t03i6lnljd71md827s4nn6pa7lse3bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUjianLearningx.RunnerTests',
  );
}
